apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: web-app-prod
  namespace: argocd
  # ðŸŽ¯ STEP 3: Annotation to subscribe to the sync-failed alert on a specific channel
  annotations:
    notifications.argoproj.io/subscribe.on-sync-failed.slack: '#ops-alerts' # <-- CHANGE THIS to your Slack Channel
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    # The namespace where the Kubernetes manifests will be deployed
    namespace: web-app-prod 
  source:
    # ðŸ“ CHANGE THIS to your actual Git repository URL
    repoURL: https://github.com/navneet1075/argocd-sample.git
    # The folder containing the deployment.yaml and service.yaml
    path: sample 
    targetRevision: HEAD 
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true