apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-argocd-app
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  source:
    repoURL: https://github.com/navneet1075/argocd-sample.git
    path: sample
    targetRevision: HEAD

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
